name: "Bot-Ross"
description: "A friendly bot that paints happy little trees."
version: "1.0.0"
slug: "bot-ross"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
